#!/usr/bin/env python3
"""
Conventional Commits validator for git commit-msg hook.

Validates that commit messages follow the format:
    <type>(<scope>): <subject>
or:
    <type>: <subject>

Allowed types: feat, fix, docs, test, refactor, chore, ci, perf
"""

import re
import sys
from pathlib import Path

CONVENTIONAL_PATTERN = re.compile(
    r"^(feat|fix|docs|test|refactor|chore|ci|perf)(\([a-z0-9_-]+\))?!?: .+"
)


def main() -> int:
    if len(sys.argv) < 2:
        print("[ERROR] Commit message file path not provided.", file=sys.stderr)
        return 1

    commit_msg_file = Path(sys.argv[1])
    if not commit_msg_file.exists():
        print(f"[ERROR] Commit message file not found: {commit_msg_file}", file=sys.stderr)
        return 1

    # Read the first non-comment line of the commit message
    lines = commit_msg_file.read_text(encoding="utf-8", errors="replace").splitlines()
    non_comment_lines = [line.strip() for line in lines if line.strip() and not line.strip().startswith("#")]

    if not non_comment_lines:
        print("[ERROR] Commit message cannot be empty.", file=sys.stderr)
        return 1

    first_line = non_comment_lines[0]

    # Allow merge commits and squash/revert commits automatically generated by git/GitHub
    if first_line.startswith(("Merge ", "Revert ", "Merge branch ", "Merge pull request ")):
        return 0

    if not CONVENTIONAL_PATTERN.match(first_line):
        border = "=" * 70
        print(f"\n{border}", file=sys.stderr)
        print("[ERROR] Commit message does NOT follow Conventional Commits format!", file=sys.stderr)
        print(f"{border}", file=sys.stderr)
        print(f"Received:\n  \"{first_line}\"\n", file=sys.stderr)
        print("Required Format:\n  <type>(<scope>): <description>\n  or: <type>: <description>\n", file=sys.stderr)
        print("Allowed Types:\n  feat, fix, docs, test, refactor, chore, ci, perf\n", file=sys.stderr)
        print("Real Examples for this Project:\n"
              "  feat(retrieval): add BM25 sparse index build\n"
              "  test(config): add fail-fast validation tests\n"
              "  fix(ingestion): handle corrupted PDF stream\n"
              "  docs(contributing): document branch workflow\n"
              "  chore(deps): update pinecone client to v10.0.0\n", file=sys.stderr)
        print(f"{border}\n", file=sys.stderr)
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())
