/**
 * Typed API client for the Self-Correcting RAG backend (Phases 46-48).
 *
 * Mirrors the backend contract exactly:
 * - REST  : /api/v1/documents (upload / list / process / delete)
 * - SSE   : POST /api/v1/query  (text/event-stream, Phase 43)
 *
 * SSE is consumed via fetch + ReadableStream (native EventSource cannot send
 * POST bodies). Event payloads match what `app/api/query_stream.py` emits.
 */

export const API_URL = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8000";

/** Mirrors backend settings.NLI_CONFIDENCE_THRESHOLD (Phase 36). */
export const NLI_CONFIDENCE_THRESHOLD = 0.85;

/* ────────────────────────── Document types ────────────────────────── */

export type DocumentStatus = "uploaded" | "processing" | "ready" | "failed";

export interface DocumentItem {
  document_id: string;
  filename: string;
  size_bytes?: number;
  status: DocumentStatus;
  chunk_count?: number | null;
  page_count?: number | null;
  failure_reason?: string | null;
}

export interface DocumentUploadResponse {
  document_id: string;
  filename: string;
  status: DocumentStatus;
  size_bytes: number;
}

/* ────────────────────────── Claim types ────────────────────────── */

export type VerificationStatus =
  | "pending"
  | "entailed"
  | "contradicted"
  | "neutral"
  | "unverifiable";

/** UI-ready label mirroring backend get_claim_final_status() (Phase 36). */
export type ClaimStatus =
  | "verified"
  | "needs_review"
  | "contradicted"
  | "unverifiable"
  | "pending";

export interface ClaimWithSource {
  claim_id: string;
  claim_text: string;
  source_chunk_id: string;
  source_text?: string | null;
  page_number?: number | null;
  page_number_end?: number | null;
  is_valid_source: boolean;
  document_id?: string | null;
  filename?: string | null;
  verification_status: VerificationStatus | null;
  confidence?: number | null;
  /** True when this claim was re-generated by the correction loop (Phase 46 touch-up). */
  was_corrected?: boolean;
}

/**
 * Replicates backend `get_claim_final_status()` so badges stay in lockstep
 * with the server's verification semantics:
 *  - unverifiable: invalid/missing source chunk
 *  - contradicted: NLI contradiction
 *  - needs_review: neutral OR entailed below confidence threshold
 *  - verified    : entailed with confidence >= NLI_CONFIDENCE_THRESHOLD
 */
export function getClaimStatus(claim: ClaimWithSource): ClaimStatus {
  if (!claim.is_valid_source || claim.verification_status === "unverifiable") {
    return "unverifiable";
  }
  switch (claim.verification_status) {
    case "contradicted":
      return "contradicted";
    case "neutral":
      return "needs_review";
    case "entailed": {
      const confidence = claim.confidence ?? 0;
      return confidence >= NLI_CONFIDENCE_THRESHOLD ? "verified" : "needs_review";
    }
    default:
      return "pending";
  }
}

/* ────────────────────────── SSE event types ────────────────────────── */

export interface RetrievalChunk {
  chunk_id: string;
  score: number;
  metadata: Record<string, unknown>;
}

export type SseEvent =
  | { type: "retrieval_started"; query: string; document_id: string | null }
  | { type: "retrieval_complete"; chunk_count: number; chunks: RetrievalChunk[] }
  | { type: "generation_started"; chunk_count: number }
  | { type: "generation_complete"; claim_count: number }
  | { type: "verification_started"; retry_count: number }
  | {
      type: "verification_complete";
      claims: ClaimWithSource[];
      retry_count: number;
    }
  | {
      type: "correction_triggered";
      retry_count: number;
      max_retries: number;
      failed_claims: ClaimWithSource[];
    }
  | {
      type: "final_answer";
      final_status: string;
      final_answer_text: string;
      claims: ClaimWithSource[];
      retry_count: number;
      retrieved_chunks: RetrievalChunk[];
      latency_ms: number;
    }
  | { type: "error"; error: string; detail: string };

export interface StreamQueryOptions {
  query: string;
  documentId?: string | null;
  enableCorrection?: boolean;
  signal?: AbortSignal;
  onEvent: (event: SseEvent) => void;
}

/** Parses one SSE block ("event: x\ndata: {...}") into a typed SseEvent. */
function parseSseBlock(block: string): SseEvent | null {
  let eventName = "message";
  const dataLines: string[] = [];
  for (const line of block.split("\n")) {
    if (line.startsWith("event:")) eventName = line.slice(6).trim();
    else if (line.startsWith("data:")) dataLines.push(line.slice(5).trim());
  }
  if (dataLines.length === 0) return null;

  const payload = JSON.parse(dataLines.join("\n")) as Record<string, unknown>;
  const type = (eventName || (payload.stage as string) || "message") as SseEvent["type"];

  switch (type) {
    case "retrieval_started":
      return {
        type,
        query: String(payload.query ?? ""),
        document_id: (payload.document_id as string | null) ?? null,
      };
    case "retrieval_complete":
      return {
        type,
        chunk_count: Number(payload.chunk_count ?? 0),
        chunks: (payload.chunks as RetrievalChunk[]) ?? [],
      };
    case "generation_started":
      return { type, chunk_count: Number(payload.chunk_count ?? 0) };
    case "generation_complete":
      return { type, claim_count: Number(payload.claim_count ?? 0) };
    case "verification_started":
      return { type, retry_count: Number(payload.retry_count ?? 0) };
    case "verification_complete":
      return {
        type,
        claims: (payload.claims as ClaimWithSource[]) ?? [],
        retry_count: Number(payload.retry_count ?? 0),
      };
    case "correction_triggered":
      return {
        type,
        retry_count: Number(payload.retry_count ?? 0),
        max_retries: Number(payload.max_retries ?? 0),
        failed_claims: (payload.failed_claims as ClaimWithSource[]) ?? [],
      };
    case "final_answer":
      return {
        type,
        final_status: String(payload.final_status ?? "unverifiable"),
        final_answer_text: String(payload.final_answer_text ?? ""),
        claims: (payload.claims as ClaimWithSource[]) ?? [],
        retry_count: Number(payload.retry_count ?? 0),
        retrieved_chunks: (payload.retrieved_chunks as RetrievalChunk[]) ?? [],
        latency_ms: Number(payload.latency_ms ?? 0),
      };
    case "error":
      return {
        type,
        error: String(payload.error ?? "STREAM_ERROR"),
        detail: String(payload.detail ?? "Unknown pipeline error."),
      };
    default:
      return null;
  }
}

export interface ApiErrorPayload {
  error?: string;
  detail?: string;
  status_code?: number;
}

export class ApiError extends Error {
  status: number;
  code: string;

  constructor(status: number, code: string, message: string) {
    super(message);
    this.name = "ApiError";
    this.status = status;
    this.code = code;
  }
}

async function parseErrorResponse(res: Response): Promise<ApiError> {
  let code = "HTTP_ERROR";
  let message = `Request failed with status ${res.status}.`;
  try {
    const body = (await res.json()) as ApiErrorPayload;
    code = body.error ?? code;
    message = body.detail ?? message;
  } catch {
    /* non-JSON error body */
  }
  return new ApiError(res.status, code, message);
}

/* ────────────────────────── REST functions ────────────────────────── */

export async function getDocuments(): Promise<DocumentItem[]> {
  const res = await fetch(`${API_URL}/api/v1/documents`, { cache: "no-store" });
  if (!res.ok) throw await parseErrorResponse(res);
  const data = (await res.json()) as { documents: DocumentItem[]; total: number };
  return data.documents ?? [];
}

export async function uploadDocument(file: File): Promise<DocumentUploadResponse> {
  const formData = new FormData();
  formData.append("file", file);
  const res = await fetch(`${API_URL}/api/v1/documents/upload`, {
    method: "POST",
    body: formData,
  });
  if (!res.ok) throw await parseErrorResponse(res);
  return (await res.json()) as DocumentUploadResponse;
}

export async function processDocument(documentId: string): Promise<void> {
  const res = await fetch(`${API_URL}/api/v1/documents/${documentId}/process`, {
    method: "POST",
  });
  if (!res.ok) throw await parseErrorResponse(res);
}

export async function deleteDocument(documentId: string): Promise<void> {
  const res = await fetch(`${API_URL}/api/v1/documents/${documentId}`, {
    method: "DELETE",
  });
  if (!res.ok) throw await parseErrorResponse(res);
}

/* ────────────────────────── SSE streaming ────────────────────────── */

/**
 * Opens the Phase 43 SSE endpoint with a POST body and dispatches typed
 * events as they arrive. Resolves when the stream closes, rejects on network
 * or HTTP-level errors (RATE_LIMIT_EXCEEDED, GENERATION_ERROR, ...).
 */
export async function streamQuery({
  query,
  documentId,
  enableCorrection = true,
  signal,
  onEvent,
}: StreamQueryOptions): Promise<void> {
  const res = await fetch(`${API_URL}/api/v1/query`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Accept: "text/event-stream",
    },
    body: JSON.stringify({
      query,
      document_id: documentId ?? null,
      enable_correction: enableCorrection,
      stream: true,
    }),
    signal,
  });

  if (!res.ok) throw await parseErrorResponse(res);
  if (!res.body) throw new ApiError(0, "STREAM_ERROR", "Response body is empty.");

  const reader = res.body.getReader();
  const decoder = new TextDecoder();
  let buffer = "";

  while (true) {
    const { value, done } = await reader.read();
    if (done) break;
    buffer += decoder.decode(value, { stream: true });

    const blocks = buffer.split("\n\n");
    buffer = blocks.pop() ?? "";

    for (const block of blocks) {
      if (!block.trim()) continue;
      try {
        const event = parseSseBlock(block);
        if (event) onEvent(event);
      } catch {
        // Malformed/mid-stream chunk — ignore and keep consuming the stream.
      }
    }
  }
}
